alert("Hello!")
let numb1 = prompt("digite o primeiro número")
//alert(typeof numb1)

let numb2 = prompt("digite o segundo número")
let iguais = Number(numb1) == Number(numb2)
let adição = Number(numb1) + Number(numb2)
let subtração = Number(numb1) - Number(numb2)
let multipl = Number(numb1) * Number(numb2)
let divisao = Number(numb1) / Number(numb2)
let rest = Number(numb1) % Number(numb2)

alert("os números insiridos são iguais: " + iguais)
alert("a soma dos dois números é: " + adição)
//alert("a soma dos dois números são par: " + iguais)
alert("a subtração dos dois números é: " + subtração)
alert("a multiplicação dos dois números é: " + multipl)
alert("a divisão dos dois números é: " + divisao)
alert("o resto da divisão dos dois números é: " + rest)
